name: PHPUnit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  phpunit:
    name: P${{ matrix.php }} - L${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4]
        laravel: [^7.0, ^8.0]
        include:
          - laravel: ^8.0
            testbench: ^6.0
          - laravel: ^7.0
            testbench: ^5.0
    steps:
    - name: Chekcout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      run: |
        composer require "illuminate/database:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --prefer-dist --no-progress --no-suggest

    - name: Execute tests
      run: vendor/bin/phpunit
