name: tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --no-interaction --no-update

      - name: Execute tests
        run: vendor/bin/phpunit
